import { RoomStatusEnum } from "../models/RoomStatus.js";

export class Room {
  constructor(
    private readonly id: string | null, // null before DB insertion
    private readonly room_name: string,
    private readonly room_code: string | null, // generated by Postgres
    private host_id: number,
    private readonly created_at: string | null,
    private status: RoomStatusEnum,
  ) {}

  public getId(): number {
    if (!this.id) throw new Error("Room ID is not set.");
    return Number.parseInt(this.id);
  }

  public getRoomName(): string {
    return this.room_name;
  }

  public getHostId(): number {
    return this.host_id;
  }

  public getStatus(): RoomStatusEnum {
    return this.status;
  }

  public verifyOwnership(requestingUserId: number): void {
    if (this.host_id !== requestingUserId) {
      throw new Error(
        `User ${requestingUserId} is not authorized to modify room ${this.id}:${this.room_name}.`,
      );
    }
  }

  public validateRoomCode(roomCode: string): void {
    if (this.room_code !== roomCode) {
      throw new Error(
        `Room code ${roomCode} is not incorrect for room ${this.id}:${this.room_name}.`,
      );
    }
  }

  public validateRoomStatus(): void {
    if (this.status === RoomStatusEnum.CLOSED) {
      throw new Error(`Room ${this.id}:${this.room_name} has been closed.`);
    }
  }

  public static createRoom(
    roomName: string,
    hostId: number,
    initialStatus: RoomStatusEnum,
  ): Room {
    return new Room(null, roomName, null, hostId, null, initialStatus);
  }

  // check room status
  // if room status is closed throw error
  // check ownership
  // if ownership transfer room host to next member if available, if not, close room
  // void

  public leaveRoom(leavingUserId: number, newHostId: number | null): void {
    this.validateRoomStatus();

    if (!newHostId) {
      this.status = RoomStatusEnum.CLOSED;
    }

    if (leavingUserId === this.getHostId() && newHostId) {
      this.host_id = newHostId;
    }
  }
}
