import { RoomStatusEnum } from "../models/RoomStatus.js";

export class Room {
  constructor(
    private readonly id: string | null, // null before DB insertion
    private readonly roomName: string,
    private readonly roomCode: string | null, // generated by Postgres
    private hostId: number,
    private readonly createdAt: string | null,
    private status: RoomStatusEnum,
  ) {}

  public getId(): number {
    if (!this.id) throw new Error("Room ID is not set.");
    return Number.parseInt(this.id);
  }

  public getRoomName(): string {
    return this.roomName;
  }

  public getHostId(): number {
    return this.hostId;
  }

  public getStatus(): RoomStatusEnum {
    return this.status;
  }

  public isRoomHost(requestingUserId: number): boolean {
    return this.hostId === requestingUserId;
  }

  public validateOwnership(requestingUserId: number): void {
    if (this.hostId !== requestingUserId) {
      throw new Error(
        `User ${requestingUserId} is not authorized to modify room ${this.id}:${this.room_name}.`,
      );
    }
  }

  public validateRoomCode(roomCode: string): void {
    if (this.roomCode !== roomCode) {
      throw new Error(
        `Room code ${roomCode} is not incorrect for room ${this.id}:${this.room_name}.`,
      );
    }
  }

  public validateRoomStatus(): void {
    if (this.status === RoomStatusEnum.CLOSED) {
      throw new Error(`Room ${this.id}:${this.roomName} has been closed.`);
    }
  }

  public static createRoom(
    roomName: string,
    hostId: number,
    initialStatus: RoomStatusEnum,
  ): Room {
    return new Room(null, roomName, null, hostId, null, initialStatus);
  }

  public leaveRoom(leavingUserId: number, newHostId: number | null): void {
    this.validateRoomStatus();

    if (!newHostId) {
      this.status = RoomStatusEnum.CLOSED;
    }

    if (leavingUserId === this.getHostId() && newHostId) {
      this.hostId = newHostId;
    }
  }
}
